### ISSUE TITLE
File ownership anomalies

### ISSUE THREAD

**Issue by rr-** [fbarriga/fuse_xattrs#3]
First I create two test directories and bind one to another:
```console
rr-@tornado:~$ mkdir a b
rr-@tornado:~$ fuse_xattrs -o allow_other a b
```

I create a file as my user:

```console
rr-@tornado:~$ echo test >b/my_file
```

I create a file as root:

```console
rr-@tornado:~$ sudo su
[sudo] password for rr-:
root@tornado:/home/rr-$ echo test2 >b/root_file
root@tornado:/home/rr-$
```

Let's examine ownership:

```
rr-@tornado:~$ la b
total 8
-rw-r--r-- 1 rr- rr- 5 Mar 16 21:13 my_file
-rw-r--r-- 1 rr- rr- 6 Mar 16 21:13 root_file
```

Both are owned by the user that mounted the directory.

If I repeat the steps in the source directory, I get expected ownership:

```console
rr-@tornado:~$ cd a
rr-@tornado:~/a$ rm my_file root_file
rr-@tornado:~/a$ touch my_file
rr-@tornado:~/a$ sudo touch root_file
rr-@tornado:~/a$ la
total 0
-rw-r--r-- 1 rr-  rr-  0 Mar 16 21:17 my_file
-rw-r--r-- 1 root root 0 Mar 16 21:17 root_file
```

**Comment by rr-** [comment]
The solution is to apply UID and GID for newly created files based on [`fuse_context`](https://libfuse.github.io/doxygen/structfuse__context.html).

`passthrough.c` which seems to be taken directly from libfuse examples doesn't do that.

**Comment by ecdlguy** [comment]
@fbarriga Is this project dead? Please merge the pull requests and release. Thanks!
